---
# PLAY1 - web1
# (1) 방화벽 서비스 내리기 - http(80/tcp), https(443/tcp) ==> firewalld
# (2) 서비스 내리기 - httpd ==>service
# (3) 서비스 설정 삭제 - /var/www/html/index.html ==> file
# (4) 패키지 삭제 - httpd, mod_ssl =>yum


# PLAY1 - web1
- name:  web1 remove
  hosts: web1
  # (1) 방화벽 서비스 내리기 - http(80/tcp), https(443/tcp) ==> firewalld
  tasks: 
    - name: 방화벽 서비스 내리기 - http(80/tcp), https(443/tcp) ==> firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - 80/tcp
        - 443/tcp
        # (2) 서비스 내리기 - httpd ==>service      
    - name: 서비스 내리기 - httpd ==>service   
      service: 
        name: httpd
        state: stopped
        enabled: no
# (3) 서비스 설정 삭제 - /var/www/html/index.html ==> file
    - name: 서비스 설정 삭제 - /var/www/html/index.html ==> file
      file:
        path: /var/www/html/index.html
        state: absent
# (4) 패키지 삭제 - httpd, mod_ssl =>yum
    - name: 패키지 삭제 httpd, mod_ssl =>yum
      yum: 
        name:
          - httpd
          - mod_ssl
        state: absent


# (2) 서비스 내리기 - httpd ==>service
# (3) 서비스 설정 삭제 - /var/www/html/index.html ==> file
# (4) 패키지 삭제 - httpd, mod_ssl =>yum
