---
- name: 웹 서비스 설정 및 기동 예제
  hosts: ansible1.example.com
  gather_facts: yes
  vars_files: 
  - vars/variables.yml
  tasks: 
  # (1) 패키지 설치
  # * httpd , mod_ssl
  - name: (1) 웹 관련 패키지 설치
    yum:
      name: 
        - "{{ pkg_http }}"
        - "{{ pkg_https }}"
      state: latest
  - name: (2) /etc/httpd/httpd.conf 작업
    copy: 
      src: "{{ conf_src_web }}"
      dest: "{{ conf_dest_web }}"
  - name: (2-1)"/var/www/html/index.html" 
    copy:
      # ansible1 192.168.10.11 has been customized by Ansible
      # "{{ ansible_fqdn }}"
      # "{{ ansible_facts['fqdn'] }}"
      content: | 
        hostname: {{ ansible_facts['hostname'] }}
        ip addr: {{ ansible_default_ipv4.address }}
      dest: "{{ index_dest_web }}"
  - name: (2-2)
    copy:
      src: "{{ htaccess_src }}"
      dest: "{{ htaccess_dest }}"
  - name: (2-3) /etc/httpd/secrets 디렉토리 생성
    file: 
      path: "{{ secrets_dir}}"
      state: directory
      owner: apache
      group: apache
      mode: '0700'
  - name: (2-4) /etc/httpd/secrets/htpasswd 파일 작업
    copy:
      src: "{{ secrets_src }}"
      dest: "{{ secrets_dest }}"
      owner: apache
      group: apache
      mode: '0400'
  - name: (3) 웹 서비스 기동
    service:
      name: "{{ svc_web }}"
      state: started
      enabled: yes #부팅시 상태
  - name: (4) 방화벽 등록
    firewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes 
      state: enabled
    loop:
      - "{{ fw_http }}"
      - "{{ fw_https }}"

## 웹
- name: 웹 요청
  hosts: localhost
  gather_facts: no
  become: no
  vars_files:
  - secrets/mysecrets.yml
  tasks:
  - name: 웹 서버에 연결 및 인증
    uri:
      url: https://ansible.example.com
      validate_certs: no
      user: "{{ loginuser }}"
      password: "{{ loginpass }}"
      force_basic_auth: yes
      status_code: 200
    register: auth_output
  - debug: var=auth_output




  # /var/www/html/index.html
  # /var/www/html/.htaccess
  # /etc/httpd/secrets/htpasswd

  # (3) 웹 서비스 기동
  # (4) 방화벽 서비스 등록
  # (5) 클라이언트에서 웹 요청