---
- name: /etc/motd 파일 배포한거 삭제
  hosts: all
  gather_facts: no
  vars: 
  - system_owner: webmaster@example.com
  tasks: 
  - name: /etc/motd 파일을 4대의 서버에 배포하기
    file:
      path: /etc/motd
      state: absent
    file:
      path: /etc/motd
      state: touch
#    shell:
#      cmd: '> /etc/motd'
