---
- name: Task Failure Exercise restore
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check local time
      command: date

    - name: Stop {{ db_service }} service
      service:
        name: "{{ db_service }}"
        state: stopped

    - name: Remove {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: absent

    - name: Remove {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: absent

    