---
- name: 각 데이터 센터 시간 동기화 
  hosts: datacenters
#  vars:
#    timesyn_ntp_servers:
#    - hostname: time.bora.net
#    iburst: true
  roles:
  - rhel-system-roles.timesync

  post_tasks:
    - name: Set timezone
      timezone:
        name: "{{ host_timezone }}"
      notify: restart_chronyd

  handlers:
  - name: restart_chronyd
    service:
      name: chronyd
      state: restart